# Generated by Django 4.2.25 on 2025-11-01 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LearningRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(db_index=True, max_length=64)),
                ('idempotency_key', models.CharField(max_length=64)),
                ('word_count', models.PositiveIntegerField()),
                ('start_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('end_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'indexes': [models.Index(fields=['user_id', 'end_at'], name='idx_user_end'), models.Index(fields=['user_id', 'start_at'], name='idx_user_start')],
            },
        ),
        migrations.AddConstraint(
            model_name='learningrecord',
            constraint=models.UniqueConstraint(fields=('user_id', 'idempotency_key'), name='uq_user_idempotency'),
        ),
    ]
